//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _3ISIP_121_Gushchin_Moroz_Dictionary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        public string Term { get; set; }
        public string Definition { get; set; }
        public string Source { get; set; }
    }
}
